### ISSUE TITLE
Question about the training speed 

### ISSUE THREAD

**Issue by ning-yuan** [hansonchen1996/MMGL#1]
Dear sir，
  I have the same question about speed about Lba in https://github.com/cvlab-yonsei/LbA/issues/2. Did you fix the question about the train speed ? I will appreciate it if you could share any information about this problem. By the way I also try to train  in RTX2080 ti.

**Comment by hansonchen1996** [comment]
Hi,
Thanks for your attention. Recently, I have updated my experimental hardware, and found that LbA ran fast on an **Nvidia 3080Ti** GPU. I also carefully checked the source code of LbA. But I think there is no significantly time-consuming operation in their implementation. So, I suggest that 3080Ti is a better choice to solve the speed issue. I hope you find this information helpful.
